swagger: '2.0'
info:
  version: v2
  title: User transaction
  description: Transaction API for argent Back OCR project 13
  termsOfService: None
  contact:
    name: Andy Ramaroson
host: localhost:3001
basePath: /api/v1
paths:
  /user/accounts:
     get:
      security:
        - Bearer: []
      tags:
        - User transaction Module
      summary: Recover bank accounts
      description: API for fetching a user profile to recover bank accounts
      parameters:
        - in: header
          type : string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Retrieve all user's bank accounts successully
          schema:
            $ref: '#/definitions/Accounts'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
  /user/accounts/id:
     get:
      security:
        - Bearer: []
      tags:
        - User transaction Module
      summary: Recover bank account
      description: API for fetching a user profile to recover bank account
      parameters:
        - in: header
          type : string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: retrieve user's bank account successully
          schema:
            $ref: '#/definitions/TransactionsDetails'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
  /user/accounts/transactions/id:
     put:
      security:
        - Bearer: []
      tags:
        - User transaction Module
      summary: Update information transaction
      description: API for fetching a user profile
      parameters:
        - in: header
          type : string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved and update successully
          schema:
            $ref: '#/definitions/TransactionsEdit'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header 

definitions:
  Accounts:
    type: object
    description : Accounts lists for this user
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description : id of account
            example: d290f1ee-6c54-4b01-90e6-d701748f0851
          name:
            type: string
            description: name of account
            example: Compte courant
          balance:
            type: integer
            description: balance of the Account
            example: 1000,00
            
  TransactionsDetails:
    type: object
    description : transaction lists for the current month
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description : id of transaction
            example: d290f1ee-6c54-4b01-90e6-d701748f0851
          amount:
            type: string
            description: transaction amount($)
            example: 100,00
          date:
            format: date-time
            example: 2016-08-29T09:12:33.001+0000
            description: transaction date
            type: string
          description:
            type: string
            description: description of the transaction
            example: Golden sun Bakery
          type:
            type: string
            description: type of transaction
            example: Deposit
          comment:
            type: string
            description: notes of transaction
            example: Transfer from my current account
          category:
            type: string
            description: category of transaction
            example: Food
  
  TransactionsEdit:
    type: object
    description : transaction lists for the current month
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description : id of transaction
            example: d290f1ee-6c54-4b01-90e6-d701748f0851
          category:
            type: string
            description: category of transaction
            example: Food
          comment:
            type: string
            description: notes of transaction
            example: Catering expenses
  
